# Generated by Django 3.1 on 2020-09-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0011_auto_20200902_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='status',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
    ]
