# Generated by Django 3.1 on 2020-09-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadcriminal_status'),
        ('criminals', '0012_criminal_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criminal',
            new_name='VerifiedCriminal',
        ),
    ]
