# Generated by Django 3.1 on 2020-09-21 06:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0014_crimecategory_crimetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimetype',
            old_name='type',
            new_name='crime_type',
        ),
        migrations.AddField(
            model_name='verifiedcriminal',
            name='ctype',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='category', on_delete=django.db.models.deletion.CASCADE, to='criminals.crimetype'),
            preserve_default=False,
        ),
    ]
