# Generated by Django 3.1 on 2020-09-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0016_auto_20200921_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedcriminal',
            name='crime_type',
        ),
    ]
