# Generated by Django 3.1 on 2020-09-21 07:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0017_remove_verifiedcriminal_crime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedcriminal',
            name='crime_type',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='category', on_delete=django.db.models.deletion.CASCADE, to='criminals.crimetype'),
            preserve_default=False,
        ),
    ]
