# Generated by Django 3.1 on 2020-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0018_verifiedcriminal_crime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedcriminal',
            name='fir_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifiedcriminal',
            name='fir_photo',
            field=models.FileField(default=1, upload_to='fir/'),
            preserve_default=False,
        ),
    ]
