# Generated by Django 3.1 on 2020-09-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200909_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcriminal',
            name='status',
            field=models.TextField(blank=True, default='UNKNOWN'),
        ),
    ]
