# Generated by Django 3.1 on 2020-09-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadcriminal_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadCriminal',
        ),
    ]
