# Generated by Django 3.1 on 2020-09-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadcriminal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcriminal',
            name='fir',
            field=models.FileField(default='fir.txt', upload_to='fir/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadcriminal',
            name='fir_no',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
