# Generated by Django 3.1 on 2020-09-19 06:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_delete_uploadcriminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCriminal',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('physical_description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('crime_type', models.CharField(max_length=30)),
                ('arresting_agency', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, default='criminals/missing.jpeg', upload_to='criminals/')),
                ('status', models.TextField(blank=True, default='UNKNOWN')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='upload.cities')),
                ('state', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='upload.states')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
