# Generated by Django 3.1 on 2020-09-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_uploadcriminal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadCriminal',
        ),
    ]
