# Generated by Django 3.1 on 2020-09-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_uploadcriminal'),
        ('upload', '0006_auto_20200917_1054'),
    ]

    operations = [
    ]
