# Generated by Django 3.1 on 2020-09-21 06:36

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0015_auto_20200921_0631'),
        ('upload', '0011_auto_20200921_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcriminal',
            name='ctype',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='category', on_delete=django.db.models.deletion.CASCADE, to='criminals.crimetype'),
            preserve_default=False,
        ),
    ]
