# Generated by Django 3.1 on 2020-09-21 06:41

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0016_auto_20200921_0641'),
        ('upload', '0012_uploadcriminal_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcriminal',
            name='ctype',
        ),
        migrations.AlterField(
            model_name='uploadcriminal',
            name='crime_type',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='category', on_delete=django.db.models.deletion.CASCADE, to='criminals.crimetype'),
        ),
    ]
